name: build psabpf

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt -y install iproute2 make cmake gcc git libgmp-dev libelf-dev zlib1g-dev libjansson-dev
        git submodule update --init libbpf
        ./build_libbpf.sh

    # Build static library version of psabpf
    - name: Build static
      run: |
        mkdir build && pushd build || exit
        cmake ..
        make -j$(nproc)
        sudo make install
        popd || exit

    # Build shared library version of psabpf
    - name: Build shared
      run: |
        mkdir build_shared && pushd build_shared || exit
        cmake -DBUILD_SHARED=on ..
        make -j$(nproc)
        sudo make install
        popd || exit
