name: Build Docker images

#on:
#  push:
#    branches: [ master ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nikss:
    if: ${{ github.repository == 'NIKSS-vSwitch/nikss' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t nikss:latest .
      - name: Docker push
        run: |
          docker login -u osinstom -p '${{ secrets.DOCKER_PASSWD }}'
          docker tag nikss:latest osinstom/nikss:latest
          docker push osinstom/nikss:latest
      - name: Logout from Docker Registry
        if: ${{ always() }}
        run: docker logout
